/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoddyHome: typeof import('./src/components/BoddyHome.vue')['default']
    CabecalhoHome: typeof import('./src/components/CabecalhoHome.vue')['default']
    FavoritosProd: typeof import('./src/components/FavoritosProd.vue')['default']
    ProductDetails: typeof import('./src/components/ProductDetails.vue')['default']
    ProductList: typeof import('./src/components/ProductList.vue')['default']
    RodaPe: typeof import('./src/components/RodaPe.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
  }
}
