/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/CarrinhoPage': RouteRecordInfo<'/CarrinhoPage', '/CarrinhoPage', Record<never, never>, Record<never, never>>,
    '/FavoritosPage': RouteRecordInfo<'/FavoritosPage', '/FavoritosPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/login/LoginPage': RouteRecordInfo<'/login/LoginPage', '/login/LoginPage', Record<never, never>, Record<never, never>>,
    '/login/RegisterPage': RouteRecordInfo<'/login/RegisterPage', '/login/RegisterPage', Record<never, never>, Record<never, never>>,
    '/products/[id]': RouteRecordInfo<'/products/[id]', '/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/products/ProductListPage': RouteRecordInfo<'/products/ProductListPage', '/products/ProductListPage', Record<never, never>, Record<never, never>>,
    '/SearchPage': RouteRecordInfo<'/SearchPage', '/SearchPage', Record<never, never>, Record<never, never>>,
  }
}
